name: mypy static type checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install tools
        run: pip3 install flake8 mypy

      - name: flake8
        run: |
          flake8 --config=setup.cfg zettarepl/

      - name: mypy
        run: |
          mypy zettarepl/
