name: mypy static type checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truenas/middleware:master

    steps:
      - uses: actions/checkout@v4

      - name: mypy
        run: |
          mypy zettarepl/
